// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/small-can-board/connectors/small.yaml
// [主板引脚名称映射 - Small CAN Board]
// 自动生成，将MCU引脚(brain_pin_e)映射到主板连接器上的物理引脚名称。
// 用于TunerStudio显示引脚功能分配，方便用户识别硬件连接。

#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::C8:
			return "C1 - Low Side";
		case Gpio::E12:
			return "C3 - Digital Input 2";
		case Gpio::E14:
			return "C2 - Digital Input 1";
		case Gpio::F11:
			return "C4 - Digital Input 3";
		case Gpio::G7:
			return "A8 - Low Side";
		case Gpio::G8:
			return "B8 - Low Side";
		default:
			return nullptr;
	}
	return nullptr;
}
