// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/main.yaml
// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/x3.yaml
// [主板引脚名称映射 - TDG PDM8]
// 自动生成，将MCU引脚(brain_pin_e)映射到主板连接器上的物理引脚名称。
// 用于TunerStudio显示引脚功能分配，方便用户识别硬件连接。

#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::PROTECTED_PIN_0:
			return "Out 1";
		case Gpio::PROTECTED_PIN_1:
			return "Out 2";
		case Gpio::PROTECTED_PIN_2:
			return "Out 3";
		case Gpio::PROTECTED_PIN_3:
			return "Out 4";
		case Gpio::PROTECTED_PIN_4:
			return "Out 5";
		case Gpio::PROTECTED_PIN_5:
			return "Out 6";
		case Gpio::PROTECTED_PIN_6:
			return "Out 7";
		case Gpio::PROTECTED_PIN_7:
			return "Out 8";
		default:
			return nullptr;
	}
	return nullptr;
}
